CREATE TABLE IF NOT EXISTS customer_profiles (
  id SERIAL PRIMARY KEY,
  lead_id INT NOT NULL UNIQUE,
  profile_type VARCHAR(50) DEFAULT 'salaried',
  sub_type VARCHAR(50),
  company_name VARCHAR(255),
  designation VARCHAR(255),
  current_job_experience_years NUMERIC(5,2),
  total_work_experience_years NUMERIC(5,2),
  net_monthly_salary NUMERIC(15,2),
  salary_credit_mode VARCHAR(50) DEFAULT 'account_transfer',
  salary_slip_available BOOLEAN DEFAULT false,
  business_name VARCHAR(255),
  business_vintage_years NUMERIC(5,2),
  professional_type VARCHAR(100),
  doctor_specialty VARCHAR(100),
  freelancer_type VARCHAR(100),
  practice_experience_years NUMERIC(5,2),
  itr_available BOOLEAN DEFAULT false,
  annual_income NUMERIC(15,2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE
);
