-- Delete all existing banks
DELETE FROM banks;

-- Insert new lenders/financiers
INSERT INTO banks (name, code, status) VALUES
('HDFC Bank', 'HDFC', 'active'),
('Axis Bank', 'AXIS', 'active'),
('ICICI Bank', 'ICICI', 'active'),
('Mahindra Finance', 'MF', 'active'),
('Equitas Small Finance Bank', 'EQUITAS', 'active'),
('Toyota Financial Services India Limited', 'TOYOTA', 'active'),
('Kotak Mahindra Prime', 'KOTAK', 'active'),
('Jana Bank', 'JANA', 'active'),
('Federal Bank', 'FEDERAL', 'active'),
('Tata Capital', 'TATA', 'active'),
('Bandhan Bank', 'BANDHAN', 'active'),
('Loans24', 'LOANS24', 'active'),
('Saraswat Bank', 'SARASWAT', 'active'),
('Muthoot Capital', 'MUTHOOT', 'active'),
('Poonawalla Fincorp Limited', 'POONAWALLA', 'active'),
('Suryoday Bank', 'SURYODAY', 'active'),
('Indostar', 'INDOSTAR', 'active'),
('ESAF Small Finance Bank', 'ESAF', 'active'),
('Vastu Finserve', 'VASTU', 'active'),
('HDB Financial Services', 'HDB', 'active'),
('IDFC First Bank', 'IDFC', 'active'),
('Cholamandalam Finance', 'CHOLA', 'active'),
('Hero Fincorp', 'HERO', 'active'),
('Bajaj Finserv Ltd', 'BAJAJ', 'active'),
('Yes Bank', 'YES', 'active'),
('TVS Credit Services', 'TVS', 'active'),
('Fortune Finance', 'FORTUNE', 'active'),
('Piramal', 'PIRAMAL', 'active'),
('AU Small Finance Bank', 'AU', 'active'),
('IndusInd Bank', 'INDUSIND', 'active'),
('RBL Bank', 'RBL', 'active'),
('Manappuram Finance Limited', 'MANAPPURAM', 'active'),
('Nissan Renault Financial Services', 'NISSAN', 'active'),
('IKF Finance', 'IKF', 'active'),
('Kogta Financial India Limited', 'KOGTA', 'active'),
('Sundram Finance', 'SUNDRAM', 'active');
